### ISSUE TITLE
✨ Feature: Include AlgoVolumeData in useAssetChartQuery

### ISSUE THREAD

**Issue by alchemist-bounty** [algodex/algodex-hooks#65]
# ℹ Overview

AlgoVolumeData is necessary to show AlgoVolume in Chart for StableAsset.
The AlgoVolumeData can't be calculated in frotnend side
It was originally created in `React` repository.
https://github.com/algodex/algodex-react/blob/926ab87787f53c9801be04d57170a0423d727ace/hooks/useAlgodex.js#L199-L211
https://github.com/algodex/algodex-react/blob/926ab87787f53c9801be04d57170a0423d727ace/hooks/useAlgodex.js#L282-L285
https://github.com/algodex/algodex-react/blob/926ab87787f53c9801be04d57170a0423d727ace/hooks/useAlgodex.js#L295-L299

### 📝 Related Issues
https://github.com/algodex/algodex-react/tree/issue-588-%E2%9C%A8_Feature_Invert_all_prices_for_stablecoin_pairs

**Comment by IYTEC** [comment]
Done
